---
title: "Introduction_to_CIA - working on the PBMC3k dataset"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction_to_CIA - working on the PBMC3k dataset}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  eval = FALSE,
  comment = "#>",
  fig.width = 8
)
```


Some code taken from https://bioconductor.org/books/3.18/OSCA.multisample/human-pbmcs-10x-genomics.html

```{r loadcia}
library("CIA")
```

```{r loadpkgs}
library("Seurat")
library("Matrix")
library("sparseMatrixStats")
library("SingleCellExperiment")
```

# CIA Vignette, reloaded

```{r}
library("TENxPBMCData")

pbmc3k <- TENxPBMCData('pbmc3k')
pbmc3k
sce <- pbmc3k
```

Some simple reprocessing:

```{r}
library("scater")
sce <- logNormCounts(sce)
sce <- runPCA(sce, ncomponents=4)
sce <- runTSNE(sce)
rowData(sce)$ave_count <- rowMeans(assay(sce, "counts"))
rowData(sce)$n_cells <- rowSums(assay(sce, "counts") > 0)
sce

colData(sce)

library("scran")
g <- buildSNNGraph(sce, k=10, use.dimred='PCA')
clust <- igraph::cluster_walktrap(g)$membership
colLabels(sce)  <- factor(clust)

plotTSNE(sce, colour_by = "label")

rownames(sce) <- rowData(sce)[["Symbol_TENx"]]
```


The "ground truth labels" would be 

```{r}
sce$label
unique(sce$label)
```

The signatures from Azimuth are here

```{r}
gmt <- load_signatures(system.file("extdata", "azimuth_human_pbmcs_level1.gmt", 
                                   package = "CIA"))
gmt
```

```{r}
scores <- score_signature(
  data = sce,
  sce_assay = "logcounts",
  geneset = gmt$`B cell`
)
head(scores)

colData(sce)$score_Bcell <- scores

plotTSNE(sce, colour_by = "label")
plotTSNE(sce, colour_by = "score_Bcell")

```

```{r}
sce_cia <- score_all_signatures(
  data = sce,
  signatures_input = gmt,
  sce_assay = "logcounts",
  return_score = FALSE,
  score_mode = "scaled",
  n_cpus = 1
)

plotTSNE(sce_cia, colour_by = "Monocyte")
plotTSNE(sce_cia, colour_by = "CD4+ T cell")
plotTSNE(sce_cia, colour_by = "CD8+ T cell")
plotTSNE(sce_cia, colour_by = "natural killer cell")
plotTSNE(sce_cia, colour_by = "B cell")
plotTSNE(sce_cia, colour_by = "other T cell")
plotTSNE(sce_cia, colour_by = "dendritic cell")
```

Running the all in one function...

```{r}
sce_aio <- CIA_classify(
  data = sce_cia,
  signatures_input = gmt,
  n_cpus = 4,
  similarity_threshold = 0,
  column_name = "CIA_prediction"
)

sce_aio <- CIA_classify(
  data = sce_aio,
  signatures_input = gmt,
  n_cpus = 4,
  similarity_threshold = 0.1,
  column_name = "CIA_prediction_t=0.1"
)


plotTSNE(sce_aio, colour_by = "CIA_prediction")
plotTSNE(sce_aio, colour_by = "CIA_prediction_t=0.1")
plotTSNE(sce_aio, colour_by = "CIA_prediction_t=0.1",
         text_by = "CIA_prediction_t=0.1")

```

TODO: rename the param column_name? cia_name?

TODO: option to ALSO store the CIA scores?

```{r compmetrics}
compute_classification_metrics(
  cells_info = colData(sce_aio),
  classification_cols = c("CIA_prediction_t=0.1"),
  ref_labels = "label"
)
```

```{r}
# removing unassigned from metrics calculation
compute_classification_metrics(
  cells_info = colData(sce_aio),
  classification_cols = c("CIA_prediction", "CIA_prediction_t=0.1"),
  ref_labels = "label",
  unassigned_label = "Unassigned"
)
```

TODO: this chunk above also needs to be made up and running


# Session info {-}

```{r sessioninfo}
sessionInfo()
```

